---

name: Run all python tests

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [master, main]
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture-name: [ "aarch64", "armhf", "armv7" ]
    env:
      LANG: de_DE.UTF-8
      LC_ALL: de_DE.UTF-8
    steps:
      - uses: actions/checkout@v4
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.architecture-name }}
          branch: latest-stable
      - name: Install python3
        run: |
          cat /etc/alpine-release
          apk add python3 python3-dev py3-pip py3-virtualenv
          python3 --version
          pip3 --version
          VIRTUAL_ENV=/opt/venv
          python3 -m venv "$VIRTUAL_ENV"
          PATH="$VIRTUAL_ENV/bin:$PATH"
          pip install -r requirements-dev.txt
        shell: alpine.sh --root {0}
      - name: Run tests
        run: |
          VIRTUAL_ENV=/opt/venv
          python3 -m venv "$VIRTUAL_ENV"
          PATH="$VIRTUAL_ENV/bin:$PATH"
          pytest tests/
        shell: alpine.sh --root {0}
