---
name: Run all python tests

# yamllint disable-line rule:truthy
on:
  # pull_request:
  #   branches: [master, main]
  # push:
  #   branches:
  #     - "**"
  #   tags:
  #     - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture-name: [ "aarch64", "x86_64" ]
    env:
      LANG: de_DE.UTF-8
      LC_ALL: de_DE.UTF-8
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@359b91e094d3dc6292e4b627abb84d8856ab7ef2 # v1.2.0
        with:
          arch: ${{ matrix.architecture-name }}
          branch: latest-stable
      - name: Install python3
        run: |
          cat /etc/alpine-release
          apk add python3 python3-dev py3-pip py3-virtualenv
          python3 --version
          pip3 --version
          VIRTUAL_ENV=/opt/venv
          python3 -m venv "$VIRTUAL_ENV"
          PATH="$VIRTUAL_ENV/bin:$PATH"
          pip install -r requirements-dev.txt
        shell: alpine.sh --root {0}
      - name: Run tests
        run: |
          VIRTUAL_ENV=/opt/venv
          python3 -m venv "$VIRTUAL_ENV"
          PATH="$VIRTUAL_ENV/bin:$PATH"
          pytest tests/
        shell: alpine.sh --root {0}
