---

name: Run all python tests

on:
  pull_request:
    branches: [master, main]
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

# cancel a currently running workflow from the same PR, branch or tag when a new workflow is triggered
# source: https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture-name: ["aarch64", "armhf", "armv7"]
    env:
      LANG: de_DE.UTF-8
      LC_ALL: de_DE.UTF-8
    steps:
      - uses: actions/checkout@v3
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.architecture-name }}
          branch: latest-stable
      - name: Install python3
        run: |
          cat /etc/alpine-release
          apk add python3 python3-dev py3-pip py3-virtualenv
          python3 --version
          pip3 --version
          VIRTUAL_ENV=/opt/venv
          python3 -m venv "$VIRTUAL_ENV"
          PATH="$VIRTUAL_ENV/bin:$PATH"
          pip install --no-cache-dir --upgrade pip
          pip install -r requirements-dev.txt
        shell: alpine.sh --root {0}
      - name: Run tests
        run: |
          VIRTUAL_ENV=/opt/venv
          python3 -m venv "$VIRTUAL_ENV"
          PATH="$VIRTUAL_ENV/bin:$PATH"
          pytest tests/
        shell: alpine.sh --root {0}