---
name: update requirements.txt and requirements-dev.txt

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.head.ref, 'dependabot/') && !startsWith(github.event.pull_request.head.ref, 'renovate/') && github.event.head_commit.author.username != 'renovate-bot')
    permissions: write-all
    strategy:
      matrix:
        python-version: [ "3" ]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@cc733854b1f224978ef800d29e4709d5ee2883e4 # v44.5.5
        with:
          files: |
            poetry.lock
            pyproject.toml
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          python -m pip install poetry
          poetry self add poetry-plugin-export
          poetry export -f requirements.txt --without dev --output requirements.txt
          poetry export -f requirements.txt --with dev --output requirements-dev.txt
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          file_pattern: "requirements*.txt"
          commit_message: update requirements.txt and requirements-dev.txt
